name: HolographicMenus
main: de.erethon.holographicmenus.HolographicMenus
version: ${project.version}${buildNo}
author: Daniel Saukel
description: ${project.description}
website: ${project.url}
softdepend: [HolographicDisplays, ProtocolLib]
api-version: 1.13
commands:
  holographicmenus:
    description: Reference command for Holographic Menus.
    aliases: [hm,m,menu]
