name: HolographicMenus
main: io.github.dre2n.holographicmenus.HolographicMenus
version: 1.0
author: Daniel Saukel
website: http://www.dre2n.ml
depend: [HolographicDisplays]
softdepend: [ProtocolLib]
commands:
  holographicmenus:
    description: HolographicMenus core command.
    aliases: [hm]
  linked:
    description: Custom linked command.
    aliases: [li,l,hml]
  menu:
    description: Command to open a holographic menu.
    aliases: [m]
permissions:
  holographicmenus.linked.op.*:
    description: Execute a linked command as an operator.
    default: op
  holographicmenus.linked.console.*:
    description: Execute a linked command as the console.
    default: op
  holographicmenus.menu.*:
    description: Open a menu.
    default: true
  holographicmenus.openclose:
    description: Open / close a menu for another player.
    default: true
  holographicmenus.reload:
    description: Reload your files.
    default: op
  holographicmenus.settings:
    description: Change your settings.
    default: true
  holographicmenus.settings.others:
    description: Change another user's settings.
    default: op
